//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group13iFinanceFix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinanceTransaction()
        {
            this.TransactionLine = new HashSet<TransactionLine>();
        }
    
        public string ID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionDescription { get; set; }
        public string authorID { get; set; }
    
        public virtual NonAdminUser NonAdminUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLine> TransactionLine { get; set; }
    }
}
