//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group13iFinanceFix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iFINANCEUser
    {
        public string ID { get; set; }
        public string UsersName { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual NonAdminUser NonAdminUser { get; set; }
        public virtual UserPassword UserPassword { get; set; }
    }
}
