//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group13iFinanceFix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterAccount()
        {
            this.TransactionLine = new HashSet<TransactionLine>();
            this.TransactionLine1 = new HashSet<TransactionLine>();
        }
    
        public string ID { get; set; }
        public string name { get; set; }
        public Nullable<double> openingAmount { get; set; }
        public Nullable<double> closingAmount { get; set; }
        public string accountGroup { get; set; }
    
        public virtual GroupTable GroupTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLine> TransactionLine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLine> TransactionLine1 { get; set; }
    }
}
