//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group13iFinanceFix.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLine
    {
        public string ID { get; set; }
        public Nullable<double> creditedAmount { get; set; }
        public Nullable<double> debitAmount { get; set; }
        public string comment { get; set; }
        public string transactionID { get; set; }
        public string firstMasterAccount { get; set; }
        public string secondMasterAccount { get; set; }
    
        public virtual FinanceTransaction FinanceTransaction { get; set; }
        public virtual MasterAccount MasterAccount { get; set; }
        public virtual MasterAccount MasterAccount1 { get; set; }
    }
}
